baseURL = 'https://davidbruchmann.github.io/crisis-tracker/'
# baseURL = 'https://davidbruchmann.github.io'
canonifyURLs = true
relativeURLs = true
languageCode = 'en-us'
title = 'Hormuz-Dubai Status | Live Logistics Utility'
# theme = 'minimal'

[params]
    description = "Live status of Strait of Hormuz, Oil prices, and Dubai logistics. Low-bandwidth optimized."
    vpn_link = "#" # Replace with your link
