name: Update-Data
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Data
        run: |

          # Create data directory if it doesn't exist
          mkdir -p data

          # Fetch Brent (Global/Middle East Benchmark)
          curl -f "https://www.alphavantage.co/query?function=BRENT&interval=monthly&apikey={{ secrets.OIL_API_KEY }}" -o data/brent.json || echo '{"data":[]}' > data/brent.json

          # Fetch WTI (US Benchmark)
          curl -f "https://www.alphavantage.co/query?function=WTI&interval=monthly&apikey={{ secrets.OIL_API_KEY }}" -o data/wti.json || echo '{"data":[]}' > data/wti.json

          # Fetch Natural Gas (LNG Status)
          curl -f "https://www.alphavantage.co/query?function=NATURAL_GAS&interval=monthly&apikey={{ secrets.OIL_API_KEY }}" -o data/gas.json || echo '{"data":[]}' > data/gas.json

          # Only overwrite if the API returns a valid JSON (not an HTML error)
          # curl -f "https://www.alphavantage.co/{{ secrets.OIL_API_KEY }}" -o data/oil_temp.json || echo "{}" > data/oil_temp.json

          # Check if it contains an error message, if not, move it to the real file
          if grep -q "Global Quote" data/brent.json; then
            mv data/oil_temp.json data/oil.json
          else
            echo "API failed or returned error. Using placeholder."
          fi
      - name: Validate JSON Files
        run: |
          # If any file contains HTML (starts with <), reset it to prevent Hugo crash
          for f in data/*.json; do
            if grep -q "^<" "$f"; then
              echo '{"data": [{"value": "0.00"}]}' > "$f"
            fi
          done

      - name: Setup Hugo
#        uses: peaceiris/actions-hugo@v2
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
